project_name: "FDN_Medical_Analysis"
seed: 42

#paths
paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  results: "results"
  logs: "results/logs"
  checkpoints: "results/models"

experiment:
  name: "Block_A_Baseline" #will change accordignly
  description: "Standard training on noisy data (No Sieve)"

noise:
  input_csv: "data/processed/train_noise_20.csv"

method:
  enable_sieve: False #set True for Block B & C (ablation)
  sieve_start_epoch: 5 #epoch to start filtering (warm up)

  use_teacher: False #set True for Block C (ablation)
  #'none' (Block B: Discard), 'soft' (Block C: Refine), 'hard' (Alternative)
  refinement_strategy: "none"

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 10
  model_name: "resnet50"

  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]

  #calculated wights
  class_weights: [4.3848, 2.7845, 1.3020, 12.4394, 1.2844, 0.2134, 10.1277]
